-- Autor: Noemi Kayama

-- ============================================================= Criação de tabelas e das chave estrangeiras =====================================================================

-- Tabela Docentes
CREATE TABLE Professor
(
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   first_name VARCHAR2(20) NOT NULL,
   surname VARCHAR2(150),
   email VARCHAR2(200) NOT NULL,
   cell_number VARCHAR2(20) NOT NULL,
   password VARCHAR2(20) NOT NULL,
   UNIQUE (email, cell_number)
);
COMMIT;


-- Tabela Instituições
CREATE TABLE Institution
(
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR2(120) NOT NULL,
   id_professor NUMBER NOT NULL
);
COMMIT;


-- Tabela Cursos
CREATE TABLE Course
(
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR2(100) NOT NULL,
   id_institution NUMBER NOT NULL
);
COMMIT;
  
-- Tabela Disciplinas
CREATE TABLE Subject
(
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR2(120) NOT NULL,
   code VARCHAR2(10) NOT NULL,
   term VARCHAR2(30) NOT NULL,
   id_course NUMBER NOT NULL
);
COMMIT;


-- Tabela Turmas
CREATE TABLE Class
(
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR2(100) NOT NULL,
   day VARCHAR2(100) NOT NULL,
   time VARCHAR2(20) NOT NULL,
   building VARCHAR2(100) NOT NULL,
   classroom VARCHAR2(10) NOT NULL,
   id_subject NUMBER NOT NULL
);
COMMIT;


-- Tabela Alunos
CREATE TABLE Student
(
   id VARCHAR2(20) PRIMARY KEY,
   name VARCHAR2(150) NOT NULL
);
COMMIT;


-- Tabela Componentes de Nota
CREATE TABLE Grade_component
(
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   name VARCHAR2(100) NOT NULL,
   code VARCHAR2(4),
   description VARCHAR2(150),
   weight NUMBER,
   id_subject NUMBER NOT NULL
);
COMMIT;


-- Tabela Notas
CREATE TABLE Grade
(
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   grade NUMBER(4,2) NOT NULL,
   id_grade_component NUMBER NOT NULL,
   id_student VARCHAR2(20) NOT NULL
);
COMMIT;


-- Tabela Auditorias
CREATE TABLE LOG_REPORT
(
   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   date_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
   old_grade NUMBER(4,2),
   new_grade NUMBER(4,2) NOT NULL,
   message VARCHAR2(100) NOT NULL,
   id_grade NUMBER NOT NULL,
   id_student VARCHAR2(20) NOT NULL,
   id_grade_component NUMBER NOT NULL,
   id_professor NUMBER NOT NULL
);
COMMIT;


-- Tabela Matrícula (entidade associativa entre Alunos e Turmas)
CREATE TABLE Registration
(
   PRIMARY KEY(id_class, id_student),
   id_class NUMBER NOT NULL,
   id_student VARCHAR2(20) NOT NULL
);
COMMIT;


-- Adicionando as Foreign Keys
ALTER TABLE Institution ADD CONSTRAINT fk_id_professor_institution FOREIGN KEY(id_professor) REFERENCES Professor (id);
ALTER TABLE Course ADD CONSTRAINT fk_id_institution_course FOREIGN KEY(id_institution) REFERENCES Institution (id);
ALTER TABLE subject ADD CONSTRAINT fk_id_course_subject FOREIGN KEY(id_course) REFERENCES Course (id);
ALTER TABLE Class ADD CONSTRAINT fk_id_subject_class FOREIGN KEY(id_subject) REFERENCES Subject (id);
ALTER TABLE Grade_component ADD CONSTRAINT fk_id_subject_component FOREIGN KEY(id_subject) REFERENCES Subject (id) ON DELETE CASCADE;
ALTER TABLE Grade ADD CONSTRAINT fk_id_component_grade FOREIGN KEY(id_grade_component) REFERENCES Grade_component (id) ON DELETE CASCADE;
ALTER TABLE Grade ADD CONSTRAINT fk_id_student_grade FOREIGN KEY(id_student) REFERENCES Student (id);
ALTER TABLE Log  ADD CONSTRAINT fk_id_grade_log FOREIGN KEY(id_grade) REFERENCES Grade (id);
ALTER TABLE Log ADD CONSTRAINT fk_id_professor_log FOREIGN KEY (id_professor) REFERENCES Professor (id);
ALTER TABLE Log_Report ADD CONSTRAINT fk_id_student_log FOREIGN KEY (id_student) REFERENCES Student (id);
ALTER TABLE Log_Report ADD CONSTRAINT fk_id_grade_comp_log FOREIGN KEY (id_grade_component) REFERENCES Grade_component (id);
ALTER TABLE Log_Report ADD CONSTRAINT fk_id_student_log FOREIGN KEY (id_student) REFERENCES Student (id);
ALTER TABLE Registration ADD CONSTRAINT fk_id_class_registration FOREIGN KEY(id_class) REFERENCES Class (id) ON DELETE CASCADE;
ALTER TABLE Registration ADD CONSTRAINT fk_id_student_registration FOREIGN KEY(id_student) REFERENCES Student (id);
ALTER TABLE log ADD CONSTRAINT fk_id_student_log FOREIGN KEY (id_student) REFERENCES Student (id);
COMMIT;

-- ===============================================================================================================================================================================

-- =============================================================================== Drops =========================================================================================


-- =====================================================================
-- Drops de tabela
-- =====================================================================
DROP TABLE STUDENT;
DROP TABLE CLASS;
DROP TABLE STUDENT_CLASS;
DROP TABLE GRADE;
DROP TABLE COURSE;
DROP TABLE GRADE_COMPONENT;
DROP TABLE subject;
DROP TABLE LOG;
DROP TABLE INSTITUTION;
DROP TABLE PROFESSOR;


-- =====================================================================
-- Drops de chaves estrangeiras
-- =====================================================================
ALTER TABLE Course DROP CONSTRAINT fk_id_institution_course;
ALTER TABLE Institution DROP CONSTRAINT fk_id_professor_institution;

-- Tabela Institution
ALTER TABLE Institution DROP CONSTRAINT fk_id_professor_institution;


-- Tabela Course
ALTER TABLE Course DROP CONSTRAINT fk_id_institution_course;


-- Tabela Subject
ALTER TABLE Subject DROP CONSTRAINT fk_id_course_subject;


-- Tabela Class
ALTER TABLE Class DROP CONSTRAINT fk_id_subject_class;


-- Tabela Grade_component
ALTER TABLE Grade_component DROP CONSTRAINT fk_id_subject_component;


-- Tabela Grade
ALTER TABLE Grade DROP CONSTRAINT fk_id_component_grade;
ALTER TABLE Grade DROP CONSTRAINT fk_id_student_grade;


-- Tabela Log
ALTER TABLE LOG DROP CONSTRAINT fk_id_grade_log;
ALTER TABLE LOG DROP CONSTRAINT fk_id_component_log;
ALTER TABLE LOG DROP CONSTRAINT fk_id_student_log;


-- Tabela Registration
ALTER TABLE Registration DROP CONSTRAINT fk_id_class_registration;
ALTER TABLE Registration DROP CONSTRAINT fk_id_student_class;


COMMIT;


-- ===============================================================================================================================================================================

-- ========================================================================== Populando tabelas ==================================================================================


-- =====================================================================
-- Inserção de Professores
-- =====================================================================
INSERT INTO Professor (first_name, surname, email, cell_number, password)
VALUES ('Beatriz', 'Naomi', 'beatriz@email.com', '19999991111', 'senha123');

INSERT INTO Professor (first_name, surname, email, cell_number, password)
VALUES ('Enzo', 'Olivato', 'enzo@email.com', '19999992222', 'senha456');

COMMIT;

-- =====================================================================
-- Inserção de Instituições
-- =====================================================================
INSERT INTO Institution (name, id_professor) VALUES ('PUC-Campinas', 1);
INSERT INTO Institution (name, id_professor) VALUES ('UNICAMP', 1);
INSERT INTO Institution (name, id_professor) VALUES ('UNESP', 2);

COMMIT;

-- =====================================================================
-- Inserção de Cursos
-- =====================================================================
INSERT INTO Course (name, id_institution) VALUES ('Engenharia de Software', 1);
INSERT INTO Course (name, id_institution) VALUES ('Ciência da Computação', 1);
INSERT INTO Course (name, id_institution) VALUES ('Engenharia de Computação', 2);
INSERT INTO Course (name, id_institution) VALUES ('Sistemas de Informação', 3);
INSERT INTO Course (name, id_institution) VALUES ('Física (Exemplo sem Disciplina)', 3);

COMMIT;

-- =====================================================================
-- Inserção de Disciplinas (Subject)
-- =====================================================================
INSERT INTO Subject (name, code, term, id_course) VALUES ('Introdução às Tecnologias Web', 'ITW101', '2º Semestre', 1);
INSERT INTO Subject (name, code, term, id_course) VALUES ('Banco de Dados', 'BD201', '3º Semestre', 1);
INSERT INTO Subject (name, code, term, id_course) VALUES ('Estrutura de Dados II', 'ED200', '4º Semestre', 2);
INSERT INTO Subject (name, code, term, id_course) VALUES ('Sistemas Operacionais', 'SO300', '5º Semestre', 3);
INSERT INTO Subject (name, code, term, id_course) VALUES ('Gestão de Projetos', 'GP400', '7º Semestre', 4);
INSERT INTO Subject (name, code, term, id_course) VALUES ('Tópicos Especiais em SI', 'TSI500', '8º Semestre', 4);

COMMIT;

-- =====================================================================
-- Inserção de Turmas (Class)
-- =====================================================================
INSERT INTO Class (day, time, building, classroom, id_subject) VALUES ('Segunda-feira', '19:00', 'Prédio C', 'Sala 101', 1);
INSERT INTO Class (day, time, building, classroom, id_subject) VALUES ('Quarta-feira', '19:00', 'Prédio C', 'Lab 5', 1);
INSERT INTO Class (day, time, building, classroom, id_subject) VALUES ('Terça-feira', '21:00', 'Prédio B', 'Sala 305', 2);
INSERT INTO Class (day, time, building, classroom, id_subject) VALUES ('Quinta-feira', '19:00', 'Prédio B', 'Lab 2', 3);
INSERT INTO Class (day, time, building, classroom, id_subject) VALUES ('Sexta-feira', '10:00', 'Prédio EC', 'CB05', 4);
INSERT INTO Class (day, time, building, classroom, id_subject) VALUES ('Segunda-feira', '08:00', 'Bloco A', 'Auditório', 5);

COMMIT;

-- =====================================================================
-- Inserção de Notas para teste da auditoria (Log_Report)
-- =====================================================================
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (8.5, 1, '25004041'); -- Nota para Ana Silva
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (7.0, 2, '25004041'); -- Nota para Ana Silva
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (9.0, 1, '25004042'); -- Nota para Bruno Costa
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (10.0, 1, '25004043'); -- Nota para Carla Almeida
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (6.5, 2, '25004043'); -- Nota para Carla Almeida
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (5.0, 3, '25004043'); -- Nota para Carla Almeida
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (7.8, 1, '25004044'); -- Nota para Daniel Ferreira
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (8.2, 1, '25004045'); -- Nota para Eduarda Santos
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (9.5, 4, '25004046'); -- Nota para Felipe Oliveira
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (6.0, 1, '25004047'); -- Nota para Giovana Rodrigues

COMMIT;

-- ===============================================================================================================================================================================

-- ============================================================================= Triggers ========================================================================================


-- =====================================================================
-- Trigger para a auditoria com o UPDATE
-- =====================================================================
CREATE OR REPLACE TRIGGER trg_report_grade -- Nome do trigger sendo criado
AFTER UPDATE OF grade ON Grade -- Trigger acontece depois de um UPDATE do atributo grade na tabela Grade
FOR EACH ROW -- Para cada uma das linhas
WHEN (NEW.grade <> OLD.grade) -- Em qualquer momento que a nota nova for maior ou menor do que a nota antiga
DECLARE -- É nessa seção que declaramos as variáveis que serão utilizadas e/ou salvas na auditoria
   -- Variáveis e seus tipos
   v_student_name VARCHAR2(150);
   v_id_professor NUMBER;
   v_message_log VARCHAR2(100);
   v_data_evento TIMESTAMP := CURRENT_TIMESTAMP; -- Explicando um operador não visto em aula: := é um operador de atribuição, indicando que o valor a ser colocado nessa variável é do tipo herdado do atribulo e de valor igual à data e horário do momento da execução
   v_data_hora_str VARCHAR2(30); -- VARCHAR que vai receber a data e hora acima formatada de acordo com o que for configurado
BEGIN -- Onde começa a operação do trigger
   -- Obtenção do nome do aluno inserido na variável v_student_name da tabela Student onde o id é o mesmo do id do UPDATE
   SELECT name INTO v_student_name
   FROM Student
   WHERE id = :NEW.id_student;

   -- Select que busca o id do professsor com base no componente de nota que foi alterado
   SELECT i.id_professor INTO v_id_professor
   FROM Grade_component gc
   JOIN Subject s ON gc.id_subject = s.id
   JOIN Course c ON s.id_course = c.id
   JOIN Institution i ON c.id_institution = i.id
   WHERE gc.id = :NEW.id_grade_component;

   -- Formatação da data/hora a partir do modelo fornecido no escopo, utilizando a variável que recebe o CURRENT_TIMESTAMP e modificando o formato
   v_data_hora_str := TO_CHAR(v_data_evento, 'DD/MM/YYYY HH24:MI:SS');

   -- Desenvolvimento da mensagem de alteração de acordo com o indicado pelos docentes no escopo do projeto
   v_message_log := ''|| v_data_hora_str || ' (Aluno ' || v_student_name || ') Nota de ' || :OLD.grade || ' para ' || :NEW.grade || ' modificada e salva!';

   -- Inserção das variáveis obtiddas dentro da tabela LOG_REPORT para registrar a ocorrência
   INSERT INTO LOG_REPORT
   (id_student, id_grade_component, old_grade, new_grade, date_time, message, id_grade, id_professor)
   VALUES
   (:NEW.id_student, :NEW.id_grade_component, :OLD.grade, :NEW.grade, v_data_evento, v_message_log, :NEW.id,v_id_professor);

   -- Exibir no Script Output a mensagem elaborada anteriormente
   DBMS_OUTPUT.PUT_LINE(v_message_log);

-- Tratamento da exceção caso ocorra algum erro no trigger
EXCEPTION
WHEN OTHERS THEN
   -- Exibe qual erro ocorreu dentro do Script Output
   DBMS_OUTPUT.PUT_LINE('Erro ao gravar o log de auditoria: ' || SQLERRM);
END;

COMMIT;


-- =====================================================================
-- Teste do trigger de UPDATE
-- =====================================================================
UPDATE Grade SET grade = 6.72
WHERE id_student = '25004043' AND id_grade_component = 1;
COMMIT;


-- =====================================================================
-- Trigger para a auditoria com o INSERT
-- =====================================================================
CREATE OR REPLACE TRIGGER trg_report_new_grade -- Nome do trigger sendo criado
AFTER INSERT ON Grade -- Trigger acontece depois de um INSERT na tabela Grade
FOR EACH ROW -- Para cada uma das linhas
WHEN (NEW.grade >= 0) -- Em qualquer momento que a nota nova for maior ou igual a zero
DECLARE -- É nessa seção que declaramos as variáveis que serão utilizadas e/ou salvas na auditoria
   -- Variáveis e seus tipos
   v_student_name VARCHAR2(150);
   v_id_professor NUMBER;
   v_message_log VARCHAR2(100);
   v_data_evento TIMESTAMP := CURRENT_TIMESTAMP; -- Explicando um operador não visto em aula: := é um operador de atribuição, indicando que o valor a ser colocado nessa variável é do tipo herdado do atribulo e de valor igual à data e horário do momento da execução
   v_data_hora_str VARCHAR2(30); -- VARCHAR que vai receber a data e hora acima formatada de acordo com o que for configurado
BEGIN -- Onde começa a operação do trigger
   -- Obtenção do nome do aluno inserido na variável v_student_name da tabela Student onde o id é o mesmo do id do INSERT
   SELECT name INTO v_student_name
   FROM Student
   WHERE id = :NEW.id_student;

   -- Select que busca o id do professsor com base no componente de nota que foi alterado
   SELECT i.id_professor INTO v_id_professor
   FROM Grade_component gc
   JOIN Subject s ON gc.id_subject = s.id
   JOIN Course c ON s.id_course = c.id
   JOIN Institution i ON c.id_institution = i.id
   WHERE gc.id = :NEW.id_grade_component;

   -- Formatação da data/hora a partir do modelo fornecido no escopo, utilizando a variável que recebe o CURRENT_TIMESTAMP e modificando o formato
   v_data_hora_str := TO_CHAR(v_data_evento, 'DD/MM/YYYY HH24:MI:SS');

   -- Desenvolvimento da mensagem de alteração de acordo com o indicado pelos docentes no escopo do projeto
   v_message_log := ''|| v_data_hora_str || ' (Aluno ' || v_student_name || ') Nota ' || :NEW.grade || ' adicionada e salva!';

   -- Inserção das variáveis obtiddas dentro da tabela LOG_REPORT para registrar a ocorrência
   INSERT INTO LOG_REPORT
   (id_student, id_grade_component, old_grade, new_grade, date_time, message, id_grade, id_professor)
   VALUES
   (:NEW.id_student, :NEW.id_grade_component, NULL , :NEW.grade, v_data_evento, v_message_log, :NEW.id,v_id_professor);

   -- Exibir no Script Output a mensagem elaborada anteriormente
   DBMS_OUTPUT.PUT_LINE(v_message_log);

-- Tratamento da exceção caso ocorra algum erro no trigger
EXCEPTION
WHEN OTHERS THEN
   -- Exibe qual erro ocorreu dentro do Script Output
   DBMS_OUTPUT.PUT_LINE('Erro ao gravar o log de auditoria: ' || SQLERRM);
END;

COMMIT;

-- =====================================================================
-- Teste do trigger de INSERT
-- =====================================================================

INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (6.5, 1, '25004052');
COMMIT;


-- ===============================================================================================================================================================================

-- ======================================================================== Comandos para testes =================================================================================

-- =====================================================================
-- Comandos para manipulação de funções e testes do código
-- =====================================================================
TRUNCATE TABLE STUDENT;
TRUNCATE TABLE REGISTRATION;
COMMIT;


DROP TABLE STUDENT;
COMMIT;


DROP TABLE REGISTRATION;
COMMIT;


DROP TABLE LOG;
DROP TABLE GRADE;
COMMIT;


SELECT * FROM GRADE_COMPONENT;


DELETE FROM GRADE_COMPONENT WHERE id = 2;


DROP TRIGGER trg_report_grade;
COMMIT;


TRUNCATE TABLE PROFESSOR;

-- ===============================================================================================================================================================================


INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (9.5, 4, '25004050'); 
INSERT INTO Grade (grade, id_grade_component, id_student) VALUES (6.0, 1, '25004050');
COMMIT;

